### ISSUE TITLE
Use a better example image for the live-cell app

### ISSUE THREAD

**Issue by constantinpape** [ilastik/bioimage-io-resources#59]
The one currently used doesn't work: https://zenodo.org/api/files/a6d477fe-9412-4064-b7e6-67f057fec920/sample_input_0.tif.
See https://github.com/ilastik/bioimage-io-resources/blob/main/src/live-cell-boundary-preview.imjoy.html#L47
Maybe we can read this from the model config?!

**Comment by oeway** [comment]
> The one currently used doesn't work: https://zenodo.org/api/files/a6d477fe-9412-4064-b7e6-67f057fec920/sample_input_0.tif. See https://github.com/ilastik/bioimage-io-resources/blob/main/src/live-cell-boundary-preview.imjoy.html#L47 Maybe we can read this from the model config?!

This one was created with a dedicated triton model, I have now removed it from the model repository, so it doesn't work anymore, we need to replace the part which calls the bioengine with the generic API, same as the mutex wathershed plugin, but a different doi, could you try that @constantinpape ?

Or maybe you don't need to but make sure the input transform / output display function will work for this mode, and we use the generic bioengine app instead.

**Comment by constantinpape** [comment]
> Or maybe you don't need to but make sure the input transform / output display function will work for this mode, and we use the generic bioengine app instead.

Let's see if we can use the generic app. No one is relying on this one to be there, it was only for test cases anyways.
I will ping you once I had time to look into the input / output functions.

(I will still leave this issue open for now, we can close it once we have the generic app working.)

**Comment by constantinpape** [comment]
We don't use this app anymore
